FROM mysql/mysql-server:latest

ENV MYSQL_ROOT_PASSWORD=password

COPY cattle.csv /tmp/cattle.csv

# Create directory for initialization scripts and copy the SQL script
RUN mkdir /docker-entrypoint-initdb.d
COPY init_db.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
